default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  host: postgres.cloud66.local
  port: 5432


development:
  <<: *default
  database: meme_backend_development

test:
  <<: *default
  database: meme_backend_test

production:
  <<: *default
  database: meme_backend_production
