default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  port: 5432
  username: <%=ENV['POSTGRESQL_USERNAME']%>
  password: <%=ENV['POSTGRESQL_PASSWORD']%>
  host: <%= ENV['POSTGRESQL_ADDRESS']%>


development:
  <<: *default
  database: meme_backend_development

test:
  <<: *default
  database: meme_backend_test

production:
  <<: *default
  database: meme_backend_production
